name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: php73-clear-linux

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --file Dockerfile --tag ${IMAGE_NAME} .

      - name: Verify if php is running
        run: |
          php_version=$(docker run --name ${IMAGE_NAME} ${IMAGE_NAME}:latest php -v)
          if [[ $php_version != *"PHP"* ]]; then
            exit 1
          fi

  push:
    needs: test

    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --file Dockerfile --tag ${IMAGE_NAME} .

      - name: Auth
        run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.GH_USER }}} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}

          docker tag ${IMAGE_NAME} ${IMAGE_ID}:latest
          docker push ${IMAGE_ID}:latest
